variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  policy: pull
  paths:
    - .cache/pip
    - env/

before_script:
  - pip install "virtualenv>=16.7.10,<20.0.0"
  - virtualenv env
  - . ./env/bin/activate
  - pip install -r dev.requirements.txt --upgrade-strategy=eager

download_deps:
  image: python:3.6-slim
  stage: download_deps
  cache:
    policy: pull-push
    paths:
      - .cache/pip
      - env/
  before_script:
    - pip install "virtualenv>=16.7.10,<20.0.0"
    - virtualenv env
    - . ./env/bin/activate
  script:
    - pip install -r dev.requirements.txt --upgrade-strategy=eager
  tags:
    - docker

.test-template:
  stage: test
  script:
    - py.test --cov-report term --cov=configue ./tests
  coverage: '/\d+\%\s*$/'
  tags:
    - docker

test-3.6:
  extends: .test-template
  image: python:3.6-slim

test-3.7:
  extends: .test-template
  image: python:3.7-slim

test-3.8:
  extends: .test-template
  image: python:3.8-slim

test-3.9:
  extends: .test-template
  image: python:3.9-rc
  allow_failure: true

lint:
  image: python:3.6-slim
  stage: test
  script:
    - pylint --load-plugins pylint_quotes configue
    - pylint --load-plugins pylint_quotes tests --disable=protected-access,too-many-instance-attributes,no-self-use
  tags:
    - docker

deploy:
  image: python:3.6-slim
  stage: deploy
  script:
    - |
      cat > ~/.pypirc << EOF
      [distutils]
      index-servers =
        pypi

      [pypi]
      username: ${PYPI_PUSH_USERNAME}
      password: ${PYPI_PUSH_PASSWORD}
      EOF
    - sed -i "s#version=\"DEV\",#version=\"${CI_COMMIT_TAG}\",#g" setup.py
    - python setup.py sdist bdist_wheel
    - twine upload -r pypi dist/configue-${CI_COMMIT_TAG}*
  tags:
    - docker
  only:
    - tags

stages:
  - download_deps
  - test
  - deploy
